#!/bin/bash

# Architecture of OS and kernel version
# The number of physical processors
# The number of Virtual Processors
# The current available RAM and its utilization rate as %
# The current available storage and its utilization rate as %
# The current utilization rate of processor as %
# Date and Time of last reboot
# Whether LVM active or not
# The number of active connections
# The number of users using the server
# The IPv4 adress of server and the MAC adress
# The number of programs executed with sudo program

{
echo -n "#Architecture: " && uname -a
echo -n "#CPU physical: " && grep "physical id" /proc/cpuinfo | sort -u | wc -l
echo -n "#vCPU: " && nproc
echo -n "#Memory Usage: " && free -m | grep Mem | awk '{printf "%d/%dMB (%.2f%%)\n", $3, $2, ($3/$2)*100}'
echo -n "#Disk Usage: " && df -m / | awk 'NR==2 {printf "%d/%.1fGb (%s)\n", $3, $2/1024, $5}'
echo -n "#CPU Load: " && mpstat 1 1 | grep "Average:" | awk '{printf "%.1f%%\n", (100 - $12)}'
echo -n "#Last boot: " && uptime -s
echo -n "#LVM use: " && lsblk -no TYPE | grep -q lvm && echo yes || echo no
echo    "#Connections TCP: " && ss -Ht state ESTABLISHED | wc -l | xargs echo -n && echo " ESTABLISHED"
echo -n "#User log: " && who | wc -l
echo    "#Network: IP $(hostname -I | awk '{print $1}') ($(ip link | grep ether | awk '{print $2}'))"
echo -n "#Sudo: $(journalctl _COMM=sudo | grep "COMMAND=" | wc -l) cmd"
} | wall
